### ISSUE TITLE
MQTT from Aquarea

### ISSUE THREAD

**Issue by MiG-41** [lsochanowski/Aquarea2mqtt#1]
Witam,
Chciałbym zainteresować Pana projektem https://github.com/Egyras/HeishaMon
Teoretycznie cel ten sam , metoda inna ( bez użycia SmartCloud).
Pozdrawiam

**Comment by lsochanowski** [comment]
Znam ten projekt problem w tym że wymaga on wpięcia dodatkowych urządzeń co rozpatrywałem ale stwierdziłem że skoro i tak potrzebuje clouda panasonica to łatwiej będzie to zrobić bez kawałka hardware'u jak/jeśli panasonic bedzie zamykał swojego clouda albo wprowadzał płatność to właśnie w tamten projekt się zmigruje

**Comment by MiG-41** [comment]
W ostatnim wydaniu jest opcja "only listen" , przez co dobrze współgra ze Smart Cloudem.
Również tamto urządzenie można wpiąć w inne gniazdo w pompie ( SmartCloud do CN-CNT , HeishaMon do CN-NMODE) , przez co aż tak dużych perturbacji to nie robi , ale ok :)

**Comment by lsochanowski** [comment]
ja nei twierdze że robi perturbacje tylko że skoro używam clouda to po co mam kupować / instalować kolejne urządzenie :)

**Comment by MiG-41** [comment]
Ok , to przy okazji , zbieramy jak najwięcej odpowiedzi pompy , żeby można było jakoś odnaleźć typ/model. Czy zechciałby się Pan podzielić taką informacją ?https://github.com/Egyras/HeishaMon/issues/13

**Comment by lsochanowski** [comment]
Jasne
